version: '3.7'

services:
  partnerapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'partner_app'
    depends_on:
      - partner_db
    ports:
      - '8080:8080'
    env_file:
      - ./app.env
    networks:
      - partner_network
  partner_db:
    image: mongo:4.0.3
    container_name: partner_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=a4905b34ddbb73573302f1b719440989
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=partnerDB
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/
      - db:/data/db
    networks:
      - partner_network
volumes:
  db:
networks:
  partner_network:
    name: partner_network